### ISSUE TITLE
貌似增加验证码登录 这个不好用了啊

### ISSUE THREAD

**Issue by mythxox** [leodas/ZhihuHelper#2]
RT

**Comment by ghost** [comment]
嗯，需要验证码了，即使是在网页上登录了也是无法删除。不知道有没有解决方法？

**Comment by leodas** [comment]
出现验证码的原因, 可能是因为多次使用错误的用户名/密码进行登录操作导致的, 没有什么好办法, 多使用浏览器一段时间应该会被取消验证码要求.
目前知乎没有开放接口, 所以只能使用模拟登录方式, 以目前的脚本形式操作, 有诸多麻烦之处.我也意识到了这点, 最理想的方式应该是以浏览器插件的形式来实现这些功能. 日后可能会提供插件工具, 不过也要等我先积累相关知识以后:)

**Comment by ghost** [comment]
thanks

---

冯剑｜Jian Feng
北京邮电大学信息与通信工程学院
无线信号处理与网络（WSPN）实验室
Email:scottfengjian@gmail.com
Tel:+86 18810718528

2014-02-21 16:26 GMT+08:00 leodas notifications@github.com:
